### ISSUE TITLE
Это точно должно быть в контроллере? А если сервис не ответит? А если нужно будет использовать в другом функционале?

### ISSUE THREAD

**Issue by forksoft** [kiboko-dev/domru-test#1]
https://github.com/kiboko-dev/domru-test/blob/b7bcb8dec0bdef0d0f05a289eeeee0e9d012d7ac/app/Http/Controllers/CurrencyController.php#L48

**Comment by kiboko-dev** [comment]
так и делалось всё это "на коленках" между собеседованиями
